version: '3'

services:
  app:
    container_name: graphql_app
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    ports:
      - 3000:3000
    tty:
      true
    volumes:
      - ./src:/go/src/app